### ISSUE TITLE
I tried to translate these Lua files into Simplified Chinese, but I don't know how to compile them into one.

### ISSUE THREAD

**Issue by Coconutat** [GreenComfyTea/RE4-Health-Bars#1]
I tried to translate these Lua files into Simplified Chinese, but I don't know how to compile them into one.I hope you can tell me how to do.This is I translated repository:https://github.com/Coconutat/RE4-Health-Bars-CN/tree/CN  
Sincerely thank you for creating this project.

**Comment by GreenComfyTea** [comment]
Oh wow, didn't expect someone to translate this mod :o 

I use [lua-amalg](https://github.com/siffiejoe/lua-amalg) to compile it into one file using this command line (you would need to put your own paths obv):

`"D:\Programs\Lua Amalg\lua54.exe" amalg.lua -o Health_Bars_precompiled.lua -d -s "E:\GitHub\RE4-Health-Bars\reframework\autorun\Health_Bars.lua" Health_Bars.bar_customization Health_Bars.config Health_Bars.customization_menu Health_Bars.drawing Health_Bars.enemy_handler Health_Bars.gui_handler Health_Bars.label_customization Health_Bars.player_handler Health_Bars.screen Health_Bars.singletons Health_Bars.time Health_Bars.utils`

But I can actually just add a proper localization support with `json` files and add your translation directly to the mod. Will allow to change the language in-game.

I have the module written, I just didn't include it, because I didn't expect small mods to be translated. Makes sense to do so now, since I also plan to port it to RE2/3/7/8.

Thank you from the bottom of my heart for helping to expand the reach of the mod, now more people will be able to enjoy it!

**Comment by Coconutat** [comment]
> Oh wow, didn't expect someone to translate this mod :o
> 
> I use [lua-amalg](https://github.com/siffiejoe/lua-amalg) to compile it into one file using this command line (you would need to put your own path obv):
> 
> `"D:\Programs\Lua Amalg\lua54.exe" amalg.lua -o Health_Bars_precompiled.lua -d -s "E:\GitHub\RE4-Health-Bars\reframework\autorun\Health_Bars.lua" Health_Bars.bar_customization Health_Bars.config Health_Bars.customization_menu Health_Bars.drawing Health_Bars.enemy_handler Health_Bars.gui_handler Health_Bars.label_customization Health_Bars.player_handler Health_Bars.screen Health_Bars.singletons Health_Bars.time Health_Bars.utils`
> 
> But I can actually just add a proper localization support with `json` files and add your translation directly to the mod. I have the module written, I just didn't include it, because I did expect small mods to be translated. Makes sense to do so, since it will allow to change the language in-game and I also plan to port it to RE2/3/7/8.

Yeah,really thanks for your help.I will try to compile it and verify if the translation is complete. Thank you again.

**Comment by Coconutat** [comment]
> Oh wow, didn't expect someone to translate this mod :o
> 
> I use [lua-amalg](https://github.com/siffiejoe/lua-amalg) to compile it into one file using this command line (you would need to put your own paths obv):
> 
> `"D:\Programs\Lua Amalg\lua54.exe" amalg.lua -o Health_Bars_precompiled.lua -d -s "E:\GitHub\RE4-Health-Bars\reframework\autorun\Health_Bars.lua" Health_Bars.bar_customization Health_Bars.config Health_Bars.customization_menu Health_Bars.drawing Health_Bars.enemy_handler Health_Bars.gui_handler Health_Bars.label_customization Health_Bars.player_handler Health_Bars.screen Health_Bars.singletons Health_Bars.time Health_Bars.utils`
> 
> But I can actually just add a proper localization support with `json` files and add your translation directly to the mod. Will allow to change the language in-game.
> 
> I have the module written, I just didn't include it, because I did expect small mods to be translated. Makes sense to do so now, since I also plan to port it to RE2/3/7/8.
> 
> Thank you from the bottom of my heart for helping to expand the reach of the mod, now more people

There is a problem now, and I am not sure if the REFramework supports the Chinese font library/UTF-8. After compilation, only Chinese characters can be displayed in the game and can only be displayed as ???? .

**Comment by GreenComfyTea** [comment]
DEL

**Comment by Coconutat** [comment]
> 

https://github.com/praydog/REFramework/issues/457#issuecomment-1186114769 
I find same issuse.But I think it will be solved.

**Comment by Coconutat** [comment]
> [REFramework Direct2D](https://www.nexusmods.com/residentevil42023/mods/83) adds UTF-8 support.

I made it!!!Right now [RE4-Health-Bars](https://github.com/GreenComfyTea/RE4-Health-Bars) support Chinese!!  
Release:https://github.com/Coconutat/RE4-Health-Bars-CN/releases/tag/CN_v0.1

**Comment by GreenComfyTea** [comment]
@Coconutat 
I committed changes for built-in localization support and added your translation. You may want to proof-read it in case I made any mistakes. There are also some new strings that need translation.

PS. Apologies for unicode support answer. I got confused and thought about the wrong thing, since both imgui and overlay text don't support unicode without extra work and both show "????" instead.

Localization file: [reframework/data/Health Bars/languages/zh-cn.json](https://github.com/GreenComfyTea/RE4-Health-Bars/blob/main/reframework/data/Health%20Bars/languages/zh-cn.json)

**Comment by Coconutat** [comment]
> @可可努特 我提交了内置本地化支持的更改并添加了您的翻译。你可能想校对一下以防我出错。还有一些新的字符串需要翻译。
> 
> 附言抱歉unicode支持答案。我感到困惑，并认为错误的事情，因为无论是imgui和覆盖文本不支持unicode没有额外的工作，都显示“？？？？"而不是。
> 
> 本地化文件：reframework/data/Health Bars/languages/zh-cn.json [reframework/data/Health Bars/languages/zh-cn.json](https://github.com/GreenComfyTea/RE4-Health-Bars/blob/main/reframework/data/Health%20Bars/languages/zh-cn.json)

It's OK,I will check it.And I think some parts of my own translation still need to be corrected. I will continue to make corrections. Thank you again for your help.

**Comment by Coconutat** [comment]
> @Coconutat I committed changes for built-in localization support and added your translation. You may want to proof-read it in case I made any mistakes. There are also some new strings that need translation.
> 
> PS. Apologies for unicode support answer. I got confused and thought about the wrong thing, since both imgui and overlay text don't support unicode without extra work and both show "????" instead.
> 
> Localization file: [reframework/data/Health Bars/languages/zh-cn.json](https://github.com/GreenComfyTea/RE4-Health-Bars/blob/main/reframework/data/Health%20Bars/languages/zh-cn.json)

Can you explain more precisely the specific meaning of "hide if no ray to player"? I find it difficult to explain it in Chinese semantics.

**Comment by Coconutat** [comment]
> @Coconutat I committed changes for built-in localization support and added your translation. You may want to proof-read it in case I made any mistakes. There are also some new strings that need translation.
> 
> PS. Apologies for unicode support answer. I got confused and thought about the wrong thing, since both imgui and overlay text don't support unicode without extra work and both show "????" instead.
> 
> Localization file: [reframework/data/Health Bars/languages/zh-cn.json](https://github.com/GreenComfyTea/RE4-Health-Bars/blob/main/reframework/data/Health%20Bars/languages/zh-cn.json)

Right now have a little bug,The "Settings" option under UI Font cannot be translated.I konw in Json had a Settings translation column.But won't work in this option.

**Comment by GreenComfyTea** [comment]
> Right now have a little bug,The "Settings" option under UI Font cannot be translated.I konw in Json had a Settings translation column.But won't work in this option.

My bad. Fixed in [663cd9d](https://github.com/GreenComfyTea/RE4-Health-Bars/commit/663cd9d4b25f443c7e0c6d656ac93a459ebdc500).

> Can you explain more precisely the specific meaning of "hide if no ray to player"? I find it difficult to explain it in Chinese semantics.

Basically, it checks if there are any obstacles between player model's origin and enemy model's origin. It is as close as I could get to check the line of sight. Without it the health bars are drawn regardless of enemies' location, for ex., behind walls. I didn't call it something like `Hide if you can't see the enemy` because there are situations when you can see the enemy even behind obstacles, for ex, fences, windows, cracks in the wall, etc.

**Comment by Coconutat** [comment]
> > Right now have a little bug,The "Settings" option under UI Font cannot be translated.I konw in Json had a Settings translation column.But won't work in this option.
> 
> My bad. Fixed in [663cd9d](https://github.com/GreenComfyTea/RE4-Health-Bars/commit/663cd9d4b25f443c7e0c6d656ac93a459ebdc500).
> 
> > Can you explain more precisely the specific meaning of "hide if no ray to player"? I find it difficult to explain it in Chinese semantics.
> 
> Basically, it checks if there are any obstacles between player model's origin and enemy model's origin. It is as close as I could get to check the line of sight. Without it the health bars are drawn regardless of enemies' location, for ex., behind walls. I didn't call it something like `Hide if you can't see the enemy` because there are situations when you can see the enemy even behind obstacles, for ex, fences, windows, cracks in the wall, etc.

I understand. Thank you for your answer.I will fix translate.

**Comment by Coconutat** [comment]
> > Right now have a little bug,The "Settings" option under UI Font cannot be translated.I konw in Json had a Settings translation column.But won't work in this option.
> 
> My bad. Fixed in [663cd9d](https://github.com/GreenComfyTea/RE4-Health-Bars/commit/663cd9d4b25f443c7e0c6d656ac93a459ebdc500).
> 
> > Can you explain more precisely the specific meaning of "hide if no ray to player"? I find it difficult to explain it in Chinese semantics.
> 
> Basically, it checks if there are any obstacles between player model's origin and enemy model's origin. It is as close as I could get to check the line of sight. Without it the health bars are drawn regardless of enemies' location, for ex., behind walls. I didn't call it something like `Hide if you can't see the enemy` because there are situations when you can see the enemy even behind obstacles, for ex, fences, windows, cracks in the wall, etc.    

***  
I think right now can release the new version.Thanks again.
